---
title: "About"
format: html
editor: visual
---

This project was developed by **Toryes** For [STA 199: Introduction to Data Science](https://sta199-s23-2.github.io/) at Duke University. The team is comprised of the following team members.

-   Owen Jennings: Owen is a sophomore at Duke University studying computer science and biology. He is originally from Durham, North Carolina, but now lives in Indianapolis, IN. He enjoys playing pickleball and building things in his free time.

-   Teddy Hur: Teddy is a sophomore studying public policy. He is from Irvine, California but currently lives in Washington Heights in New York City where his parents moved.

-   Yadira Paz-Martinez: Yadira is a sophomore studying Public Policy and Human rights on the pre-law track. She is from Clinton, NC, and during her free time, she enjoys watching documentaries, cooking, and traveling with her friends.

-   Rodricka Robinson is a junior on the pre-med track at Duke University. She studies Cultural Anthropology and Creative Writing. She is from New Orleans, Louisiana.
