---
title: "Team Toryes"
subtitle: "STA 199 Project"
format: html
editor: visual
---

The impact of the Covid-19 pandemic has been devastating to the U.S. economy. From high unemployment rates to increasing the cost of living, we are still feeling the effects of the pandemic today. The cost of rent is a prime example. As North Carolina natives and Duke students, we were interested in how COVID impacted North Carolina's fair market rent prices. We hypothesized that North Carolina counties will experienced an increase of 20% in fair market rent from 2020 to 2023. To test our hypothesis, we created visualizations and tables that looked at how rent prices changed from pre-Covid (2020) to post-Covid (2023) in North Carolina by county. While we did not adjust for inflation, our research showed the majority of counties saw a major jump in fair market rents. We hope that this research will be beneficial to both economists and apartment-seekers in North Carolina. Additionally, we recommend the use of our linear regression model to predict how rents will increase in North Carolina if trends that occurred from 2020 to 2023 continue to occur.
