---
title: "How Have Covid Change Rent Prices In North Carolina?"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

**Introduction and Data:**

For this research project, we will be investing: How has the cost of rent changed post-COVID in North Carolina? The Covid-19 pandemic delivered a huge blow to the economy, as a result, there has been a steady increase in inflation despite pay rates remaining roughly the same (CITE). This has greatly increased the cost of living with rent prices skyrocketing in multiple states(CITE). As college students, we want to analyze the extend of Covid-19's impact of rent prices in North Carolina, our home state. We will compare the rent prices of the one-bedroom, two-bedroom, three-bedroom, four-bedroom from 2019 (pre-Covid) and 2022 (post-Covid). We hypothesized that rent prices from 2019 increased by 20% post-Covid.

We will use data collected by the Department of Housing and Urban Development's Office of Public Development and Research (HUD's PD&R). Data collection started in 1983 based on surveys of local housing markets. Now, housing authorities conduct surveys on their behalf, along with accepting telephone or mail surveys. Their full collection of data is divided by year then state and then county. There is also the option to view the full state or just the county. The variables included are zip code, efficiency, one-bedroom, two-bedroom, three-bedroom, four-bedroom, and FMR percentile. The variable efficiency is defined as "the ratio of the rent estimate for Efficiency Units to the rent estimate \[certain bedroom units\]" (HUD). **(DEFINE FMR)** It is based on "the average of the past three estimates from the most recent American Community Survey 5-Year releases"(HUD). The variables, years, efficiency, one-bedroom, two-bedroom, three-bedroom, four-bedroom, and FMR percentile are quantitative variables. The variable state is a categorical variable.

Ethical concerns may involved the tenants in the property being disturbed by survey collectors or numerous telephone calls requesting for surveys. Another issue with privacy could be that a lot of tenants may not want everyone to know the rent prices of the area they live in.

**Methodology:**

(The methodology section should include visualizations and summary statistics relevant to your research question. You should also justify the choice of statistical method(s) used to answer your research question. Prediction, Interference, both?)

To test our hypothesis, we will use a linear regression model that looks how prices have changed in North Carolina as a result of Covid.

(Try to add additional variables!)

**Results:**

(Showcase how you arrived at answers to your research question using the techniques we have learned in class. Provide only the main results from your analysis)

**Sources:**

https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2023_code/2023bdrm_rent.odn?year=2023&cbsasub=METRO33860M33860&br_size=0

https://www.cbpp.org/research/poverty-and-inequality/tracking-the-covid-19-economys-effects-on-food-housing-and
