<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>COVID-19 Impacts on Rent Prices in North Carolina</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Team Toryes</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">COVID-19 Impacts on Rent Prices in North Carolina</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<!-- ██ ███    ███ ██████   ██████  ██████  ████████  █████  ███    ██ ████████  -->
<!-- ██ ████  ████ ██   ██ ██    ██ ██   ██    ██    ██   ██ ████   ██    ██     -->
<!-- ██ ██ ████ ██ ██████  ██    ██ ██████     ██    ███████ ██ ██  ██    ██     -->
<!-- ██ ██  ██  ██ ██      ██    ██ ██   ██    ██    ██   ██ ██  ██ ██    ██     -->
<!-- ██ ██      ██ ██       ██████  ██   ██    ██    ██   ██ ██   ████    ██     -->
<!-- BEFORE RENDERING: DOWNLOAD urbnmapr PACKAGE -->
<!-- Run console command: devtools::install_github("UrbanInstitute/urbnmapr") -->
<section id="introduction" class="level1">
<h1>Introduction:</h1>
<p>For this research project, we will be investigating how the COVID-19 pandemic impacted fair market rents throughout the state of North Carolina. The COVID-19 pandemic delivered a huge blow to the economy and as a result there has been a steady increase in inflation despite pay rates remaining roughly the same (Bernstein and Tedeschi). This has greatly increased the cost of living with rent prices skyrocketing in multiple states (Bernstein and Tedeschi).</p>
<p>As proud Cameron Crazies, we want to analyze the extent of COVID-19’s impact of rent prices in our own home state of North Carolina. We will compare the FMR prices of zero-bedroom, one-bedroom, two-bedroom, three-bedroom, and four-bedroom across different North Carolinians counties from 2020-2023.</p>
<p>We will use data collected by the Department of Housing and Urban Development’s Office of Public Development and Research (HUD’s PD&amp;R). HUD PD&amp;R Data collection started in 1983 based on surveys of local housing markets. Now, housing authorities conduct surveys on their behalf, along with accepting telephone or mail surveys. Their full collection of data is divided by year, then state, and then county. For the purposes of our project, we only included data from North Carolina to compare between NC counties. Our data set’s variables include state, year, county name, number of bedrooms, and Fair Market Rent (FMR) price. FMR is the amount an individual is likely to pay for rent in a particular area based on the term length listed by the landlord (HUD). They “are estimates of 40th percentile gross rents for standard quality units within a metropolitan area or nonmetropolitan county.” In addition, the “year” variable for FMR’s is based off fiscal year, which is from October 1 of the previous year to September 30th of the current year (for example FY 2020 consists of data from 10/1/19 to 9/30/20).</p>
<p>Ethical concerns may involve the tenants in the property being disturbed by survey collectors or numerous telephone calls requesting for surveys. Another issue with privacy could be that tenants may not want everyone to know the rent prices of the area they live in. There is also an ethical concern regarding the areas and individuals being surveyed and how those results could alter rent prices alongside inflation.cFor our hypothesis, we predict that most North Carolina counties saw an increase in 20% in Fair Market Rent Prices.</p>
<p>For our hypothesis, we predict that most North Carolina counties saw an increase in 20% in Fair Market Rent Prices.</p>
</section>
<section id="literature-review" class="level1">
<h1>Literature Review:</h1>
<p>https://usafacts.org/articles/where-are-rents-rising-post-covid-19/</p>
<p>The article titled, “Where are rents rising post COVID-19?,” does an overview of rent changes in the U.S. and then discusses the county and zip codes with the highest rent increase. It looks closer at Arizona and San Francisco, finding that Maricopa and Pinal counties in Arizona have the highest rent increase from 2020-2023 and that San Francisco has large rent differences by zip code. This literature also discusses in-depth the functions of FMR and how they measure final rent prices. This reading shows that COVID-19 increased rent prices but also had some outliers of counties with decreasing rent price changes. Compared to this article that reserached FMR changes throughout the U.S., we will focus on analyzing the rent price changes in North Carolina. USA Facts also has adjusted for inflation in which our research does not count for inflation.</p>
</section>
<section id="data" class="level1">
<h1>Data:</h1>
<p>Below is an explanation of the variables we will use to create our visualizations and models. Our variables were derived from a pivoted version of the Department of Housing and Urban Development’s Office of Public Development and Research data set for the years 2020 through 2023.</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>fmr</td>
<td>The fair market rent as described above for a specified number of bedrooms and year.</td>
</tr>
<tr class="even">
<td>bedrooms</td>
<td>The bedrooms variable indicates the number of bedrooms for a specific fair market rent value.</td>
</tr>
<tr class="odd">
<td>countyname</td>
<td>The county name for a specific fair market rent value.</td>
</tr>
<tr class="even">
<td>year</td>
<td>The fiscal year for which data used to calculate the fair market rent value was collected.</td>
</tr>
<tr class="odd">
<td>state_alpha</td>
<td>The state for a specific fair market rent value. In our analysis, we focused on North Carolina, so all of our observations had a state_alpha equal to “NC”.</td>
</tr>
<tr class="even">
<td>fmr_pct</td>
<td>fmr_pct is a variable that we calculated in our analysis to use in our map graph. It represents the average change in fair market rent from 2020 for a specified year by county (irregardless of # bedrooms) .</td>
</tr>
</tbody>
</table>
</section>
<section id="methodology" class="level1">
<h1>Methodology:</h1>
<div class="cell">

</div>
<section id="did-rent-increase-in-your-county-after-covid-19" class="level3">
<h3 class="anchored" data-anchor-id="did-rent-increase-in-your-county-after-covid-19">Did rent increase in your county after COVID-19?</h3>
<p><strong>North Carolina counties where fair market rent increased from 2020 to 2023</strong> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell" data-crop="true">
<div class="cell-output-display">
<p><img src="report_files/figure-html/graph%20data-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
</section>
<section id="which-counties-in-north-carolina-had-the-largest-rent-increases-after-covid-19" class="level3">
<h3 class="anchored" data-anchor-id="which-counties-in-north-carolina-had-the-largest-rent-increases-after-covid-19">Which counties in North Carolina had the largest rent increases after COVID-19?</h3>
<p><strong>North Carolina counties with fair market rent increasing by 20% or more from 2020 to 2023</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Change in Fair Market Price (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Transylvania County</td>
<td style="text-align: right;">41.52622</td>
</tr>
<tr class="even">
<td style="text-align: left;">Granville County</td>
<td style="text-align: right;">31.38713</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Hanover County</td>
<td style="text-align: right;">31.31379</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pitt County</td>
<td style="text-align: right;">29.45726</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pender County</td>
<td style="text-align: right;">28.69983</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gates County</td>
<td style="text-align: right;">28.43547</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polk County</td>
<td style="text-align: right;">28.25967</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pamlico County</td>
<td style="text-align: right;">27.26291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Davie County</td>
<td style="text-align: right;">26.74854</td>
</tr>
<tr class="even">
<td style="text-align: left;">Forsyth County</td>
<td style="text-align: right;">26.74854</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stokes County</td>
<td style="text-align: right;">26.74854</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yadkin County</td>
<td style="text-align: right;">26.74854</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tyrrell County</td>
<td style="text-align: right;">26.04116</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anson County</td>
<td style="text-align: right;">24.55669</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Watauga County</td>
<td style="text-align: right;">24.29775</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guilford County</td>
<td style="text-align: right;">23.46933</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Randolph County</td>
<td style="text-align: right;">23.46933</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cabarrus County</td>
<td style="text-align: right;">23.44487</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gaston County</td>
<td style="text-align: right;">23.44487</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mecklenburg County</td>
<td style="text-align: right;">23.44487</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Union County</td>
<td style="text-align: right;">23.44487</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lee County</td>
<td style="text-align: right;">22.99537</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumberland County</td>
<td style="text-align: right;">22.48872</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beaufort County</td>
<td style="text-align: right;">21.64400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin County</td>
<td style="text-align: right;">21.55001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Johnston County</td>
<td style="text-align: right;">21.55001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wake County</td>
<td style="text-align: right;">21.55001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bladen County</td>
<td style="text-align: right;">21.50306</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Greene County</td>
<td style="text-align: right;">21.17567</td>
</tr>
<tr class="even">
<td style="text-align: left;">Carteret County</td>
<td style="text-align: right;">21.10850</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Edgecombe County</td>
<td style="text-align: right;">20.96983</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nash County</td>
<td style="text-align: right;">20.96983</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avery County</td>
<td style="text-align: right;">20.94036</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rockingham County</td>
<td style="text-align: right;">20.66583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rutherford County</td>
<td style="text-align: right;">20.57969</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chatham County</td>
<td style="text-align: right;">20.54425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Durham County</td>
<td style="text-align: right;">20.54425</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange County</td>
<td style="text-align: right;">20.54425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stanly County</td>
<td style="text-align: right;">20.51374</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
</div>
<p>The table above lists all of the North Carolina counties that saw an increase in fair market rents over 20% or greater from the beginning of COVID-19 (2020) to the end of COVID-19 (2023). In total, 39 out of 100 North Carolina counties saw an increase in fair market rents of 20% or more.</p>
</section>
<section id="which-counties-in-north-carolina-had-the-largest-decrease-in-rents-after-covid-19" class="level3">
<h3 class="anchored" data-anchor-id="which-counties-in-north-carolina-had-the-largest-decrease-in-rents-after-covid-19">Which counties in North Carolina had the largest decrease in rents after COVID-19?</h3>
<p><strong>North Carolina counties with fair market rent decreasing from 2020 to 2023</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Change in Fair Market Price (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Camden County</td>
<td style="text-align: right;">-12.898954</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hyde County</td>
<td style="text-align: right;">-3.931737</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will use a linear regression model that looks how prices have changed in North Carolina as a result of COVID-19 and to predict future pricing if COIVD-19 pricing trends continue.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>rent_averages <span class="ot">&lt;-</span> rents <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, bedrooms) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(fmr)) <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> year <span class="sc">-</span> <span class="dv">2020</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rent_averages <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">year</th>
<th style="text-align: left;">bedrooms</th>
<th style="text-align: right;">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">633.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">651.65</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">799.12</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1062.55</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">1282.35</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">657.30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">674.45</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">825.05</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1089.86</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">1312.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">684.60</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">708.88</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">864.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1134.80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">1368.58</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">751.61</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">781.94</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">946.68</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1233.93</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">1486.67</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(mean <span class="sc">~</span> year <span class="sc">+</span> bedrooms, <span class="at">data =</span> rent_averages)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>regression <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">606.1204</td>
<td style="text-align: right;">13.879189</td>
<td style="text-align: right;">43.67117</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">50.3614</td>
<td style="text-align: right;">4.760523</td>
<td style="text-align: right;">10.57896</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bedrooms1</td>
<td style="text-align: right;">22.5675</td>
<td style="text-align: right;">16.830989</td>
<td style="text-align: right;">1.34083</td>
<td style="text-align: right;">0.2013267</td>
</tr>
<tr class="even">
<td style="text-align: left;">bedrooms2</td>
<td style="text-align: right;">177.2425</td>
<td style="text-align: right;">16.830989</td>
<td style="text-align: right;">10.53072</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bedrooms3</td>
<td style="text-align: right;">448.6225</td>
<td style="text-align: right;">16.830989</td>
<td style="text-align: right;">26.65455</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">bedrooms4</td>
<td style="text-align: right;">680.9775</td>
<td style="text-align: right;">16.830989</td>
<td style="text-align: right;">40.45974</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(regression)<span class="sc">$</span>adj.r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9925511</code></pre>
</div>
</div>
<p>The linear regression model above can be used to find <strong>estimate mean</strong> fair market rents based on our data, if the trend in prices continues, even as the effects COVID-19 dwindle. From the linear regression model we can write an equation to estimate the mean fair market rents based on the number of years that have passed since 2020 and the number of bedrooms for the accommodation.</p>
<p><span class="math display">\[
\widehat{fmr} = (50.36 * years\_since\_2020) + 606.12
\]</span></p>
<p><span class="math display">\[
+\space(22.56 * one\_bedroom) + (177.24 * two\_bedroom)
\]</span></p>
<p><span class="math display">\[
+\space(448.62 * three\_bedroom) + (680.97 * four\_bedroom)
\]</span></p>
<p><em>where one_bedroom, two_bedroom, three_bedroom, and four_bedroom are Boolean values that represent if the fair market rent based on the number of bedrooms.</em></p>
<p>Using the above linear regression model, we can find the estimate mean fair market rent (fmr) for a specified year and number of bedrooms. This prediction or estimate will be based on our data from 2020 through 2023 that we used in our data analysis.</p>
<p>For example, if we would like to predict the fair market rent of a 2 bedroom accommodation in the year 2024, we can use our linear regression model to predict the price assuming that the conditions from the years 2020 through 2023 hold:</p>
<p>$$ = (50.36 * 4) + 606.12 + (177.24 * two_bedroom)</p>
<p><span class="math display">\[ \]</span></p>
<p> = (50.36 * 4) + 606.12 + (177.24 * 1)</p>
<p><span class="math display">\[ \]</span></p>
<p> = 984.8 $$ In conclusion, from our linear regression model based on the mean FMRs from the years 2020 through 2023 in North Carolina, we can predict that a 2 bedroom accommodation in the year 2024 in North Carolina will have an estimate mean fair market rent of 984.8 dollars, holding all else constant.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results:</h1>
<p>We started with understanding the rent increases per county after COVID-19. The results of the change in fair market rent % shows that numerous counties saw an increase in rents from 2020 to 2023. One county had a 40% change in FMR, and one county had a -10% change in FRM. Most counties had a percent change of about 15-30% change. We hypothesized that North Carolina counties saw a 20% increase in fair market rents from 2020 to 2023. Our analysis showed 39 out of 100 North Carolina counties saw an increase in fair market rents of 20% or more from 2020 to 2023. Additionally, we created a linear regression to help researchers predict how fair market rents will increase in the following years if price trends that occurred during COVID-19 continue to occur.</p>
<p>We also researched which countries in NC has the largest rent increases after COVID-19. Based on our outcomes, the research indicates that Transylvania Country has the highest change in FMR, resting at 41.53% change. On the contrary we also calculated the countries in NC with the lowest rent increases after COVID-19. Camden County with -12.9% and Hyde County with -3.93% change from the fiscal year 2020 to 2023. Furthermore, we decided to dive into the FMR from 2020-2023 based on the number of bedrooms. Based on the results, each year gradually, all housing, regardless of the number of rooms increased.</p>
<p>Our data analysis does not change the fair market rents increases or decreases to account for changes in inflation. We can improve on our analysis in the future by looking the fair market rents in North Carolina adjusted to account for inflation. Calculating the percent change in rents adjusted for inflation might allow us to make further conclusions, such as which counties in the state were the most impacted by COVID-19.</p>
<p><strong>Sources:</strong></p>
<p>https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2023_code/2023bdrm_rent.odn?year=2023&amp;cbsasub=METRO33860M33860&amp;br_size=0</p>
<p>https://www.cbpp.org/research/poverty-and-inequality/tracking-the-covid-19-economys-effects-on-food-housing-and</p>
<p>https://www.huduser.gov/portal/datasets/fmr.html</p>
<p>https://www.whitehouse.gov/cea/written-materials/2021/04/12/pandemic-prices-assessing-inflation-in-the-months-and-years-ahead/</p>
<p>https://usafacts.org/articles/where-are-rents-rising-post-covid-19/</p>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p><strong>Source: HUD Fair Market Rent Data. Change in fair market rent is calculated by finding the average percent change of fair market rents from 2020 to 2023 of 0 to 4 bedroom accommodations.</strong><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>